config/routes.rb
Rails.application.routes.draw do

  root 'message#index'

  post 'message/index' => 'message#create'

  get 'api/messages' => 'message#api'

end

app/models/post.rb
require 'json'

class Post < ActiveRecord::Base

end

# Takes a Post instance
#
# Returns string formatted as JSON

def the_json_func(postsarr)
	api = Hash.new
	postsarr = time_dif(postsarr)

	postsarr.each_with_index do |post, index|
		api[index] = { name: post[:name], message: post[:message], age: time_desc(post[:dif])}
	end

	return api.to_json
end

# Compares the created_at fields for Post instance
#
# Returns number of seconds that has past since it post

def time_dif(records_arr)
	present = Time.now

	records_arr.each do |record|

		records_time = record.created_at
		record[:dif] = present - records_time

	end

	return records_arr

end

# Takes a number of seconds
#
# Returns summary of approximately how much time has past.

def time_desc(num)
	min = num/60
	hour = num/3600
	day = num/86400


	if day >= 365 and day < 730
		str = "A year"
	else
		str = (num/86400/365).to_s + " years"
	end

	if day >= 30 and day < 365
		months = day/30
		if months == 1
			str = "About a month"
		else
			str = months.to_s + " months"
		end
	end

	if day > 0 and day < 30
		if day == 1
			str = day.to_s + " day"
		else
			str = day.to_s + " days"
		end
	end

	if hour > 0 and hour < 24
		if hour == 1
			str = "An hour"
		else
			str = hour.to_s + " hours"
		end
	end

	if min > 0 and min < 60
		if min == 1
			str = "A minute"
		else 
			str = min.to_s + " minutes"
		end
	end

	if num < 60
		str = "Less than a minute"
	end

	return str + " ago"
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/message_controller.rb
require 'json'

class MessageController < ApplicationController

	def index
		@post = Post.new #for the form

		@posts = time_dif(Post.all)
	end

	def create
		post = Post.new(post_params)
		post.save
		redirect_to root_path
	end

  	def post_params
      params.require(:post).permit(:name, :message, :dif)
    end

    def api
    	posts = Post.all
        @api = the_json_func(posts)
    end	

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/message_helper.rb
module MessageHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>GradAssessment</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<h2>Welcome to the ultimate log of posted messages!</h2>
<%= yield %>

</body>
</html>

app/views/message/_form.html.erb
<%= form_for @post, url: message_index_path do |f| %>

  <div class="field">
    <%= f.label "Name" %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label "Your Message" %><br>
    <%= f.text_field :message %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>

<% end %>

app/views/message/api.html.erb
<%= @api %>

app/views/message/index.html.erb
<p>Provide your name and a brief message to post to this page!</p>

<%= render 'form' %>

<h3>Previously added posts</h3>

<table>
  	<thead>
    	<tr>
      		<th>Name</th>
      		<th>Message</th>
      		<th>Time</th>
    	</tr>
  	</thead>

	<tbody>
	    <% @posts.each do |post| %>
	      	<tr>
	        	<td><%= post.name %></td>
	        	<td><%= post.message %></td>
	        	<td><%= time_desc(post.dif) %></td>
	      	</tr>
	    <% end %>
	</tbody>
</table>